# Change these first
owner: appdesign1987 # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Hosting server
    url: https://dagobert.jeroenvd.nl
  - name: Hosting panel
    url: dagobert.jeroenvd.nl
    port: 8083
  - name: mailserver - mail ontvangen
    url: mailcow.jeroenvd.nl
    port: 587
    check: "tcp-ping"
  - name: mailserver - panel
    url: https://mailcow.jeroenvd.nl
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jeroenvd.nl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "*Server-status"
  introMessage: Onderstaand de status van de verschillende services. Deze informatie wordt elke 5 minuten bijgewerkt.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
